{{- if not (include "ctrlplane.isValueFrom" .Values.global.secrets.authSecret) }}
{{- $secretName := (include "web.fullname" .) }}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
{{- if and $existing (hasKey $existing.data "AUTH_SECRET") }}
  AUTH_SECRET: {{ index $existing.data "AUTH_SECRET" }}
{{- else }}
  AUTH_SECRET: {{ randAlphaNum 64 | b64enc }}
{{- end }}
{{- end }}
