apiVersion: v2
name: ctrlc-sync
description: A Helm chart for ctrlc sync jobs in Kubernetes
type: application
version: 0.1.4
appVersion: "0.16.3"

maintainers:
  - name: ctrlplane
    email: support@ctrlplane.com
    url: https://ctrlplane.dev
