apiVersion: v2
name: ctrlc-sync
description: A Helm chart for ctrlc sync jobs in Kubernetes
type: application
version: 0.1.0
appVersion: "v0.16.2"

maintainers:
  - name: ctrlplane
    email: support@ctrlplane.com
    url: https://ctrlplane.dev
