{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ctrlc-sync.clusterRoleBinding.k8s" . }}
  labels:
    {{- include "ctrlc-sync.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "ctrlc-sync.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "ctrlc-sync.clusterRole.k8s" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
