{{- if not (kindIs "map" .Values.ctrlc.apiKey ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctrlc-sync.secretname" . }}
  labels:
    {{- include "ctrlc-sync.labels" . | nindent 4 }}
data:
  apiKey: {{ .Values.ctrlc.apiKey | b64enc }}
{{- end }}
